apiVersion: v1
kind: Service
metadata:
  name: sheep-dog-dev-db
  labels:
    app: sheep-dog-dev
spec:
  selector:
    app: sheep-dog-dev-db
  ports:
    - name: sheep-dog-dev-db
      port: 3306
      nodePort: 30306
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: sheep-dog-dev-svc
  labels:
    app: sheep-dog-dev
spec:
  selector:
    app: sheep-dog-dev-svc
  ports:
    - name: sheep-dog-dev-svc
      port: 80
      targetPort: 8080
  type: LoadBalancer
